### ISSUE TITLE
Python3 version can't be installed on RPi3 and Raspbian

### ISSUE THREAD

**Issue by Bartyx** [rm-hull/luma.led_matrix#118]
Hey.
I am following installation instructions, but the step: "Proceed to install latest version of the library directly from PyPI: $ sudo -H pip install --upgrade luma.led_matrix" does not work.
RPi 3B and newest Raspbian NOOBS instalation.

Here is a terminal:
```
pi@raspberrypi:~ $ sudo -H pip3 install --upgrade luma.led_matrix
Collecting luma.led_matrix
  Downloading luma.led_matrix-1.0.0.tar.gz (10.3MB)
    100% |████████████████████████████████| 10.3MB 13kB/s
    Complete output from command python setup.py egg_info:
    error in luma.led_matrix setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-'"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u7akoewq/luma.led-matrix/
pi@raspberrypi:~ $
```

Can you fix it please? Thanks.

**Comment by thijstriemstra** [comment]
@Bartyx you need to upgrade your setuptools version as well. If it's not in the docs yet, it should be.

```
sudo -H pip3 install -U setuptools
```

**Comment by thijstriemstra** [comment]
Yes it's in the docs, please follow the instructions before opening a ticket: https://luma-led-matrix.readthedocs.io/en/latest/install.html#installing-from-pypi

**Comment by thijstriemstra** [comment]
@rm-hull or should we place that setuptools check in setup.py for this project as well?

**Comment by Bartyx** [comment]
@thijstriemstra I did it all! Of course i did. I followed instructions step-by-step, but it's not working. :(

**Comment by Bartyx** [comment]
Look at this:
`pi@raspberrypi:~ $ sudo -i pip install --upgrade pip setuptools

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

Requirement already up-to-date: pip in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: setuptools in /usr/local/lib/python3.4/dist-packages
pi@raspberrypi:~ $ sudo -i pip3 install --upgrade pip setuptools

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

Requirement already up-to-date: pip in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: setuptools in /usr/local/lib/python3.4/dist-packages
pi@raspberrypi:~ $ sudo -H pip3 install --upgrade luma.led_matrix
Collecting luma.led_matrix
  Using cached luma.led_matrix-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    error in luma.led_matrix setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-'"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k92hdf3i/luma.led-matrix/
pi@raspberrypi:~ $`

**Comment by rm-hull** [comment]
I think there is a typo in the setup here: https://github.com/rm-hull/luma.led_matrix/blob/master/setup.py#L30

the package name should be `rpi_ws281x` rather than `rpi-ws281x`

I will rebuild and retest

**Comment by rm-hull** [comment]
Just released **luma.led_matrix 1.0.2** with a fix for this (don't ask, ... too embarrassing!) and installed it on a RPi B2 on both py2.7 and py3.4 successfully - let me know if you hit any problems. 

Thanks for taking the time to submit a bug report.

**Comment by Bartyx** [comment]
It works fine now. Thanks for the fix.

**Comment by thijstriemstra** [comment]
I wonder why this wasn't caught by Travis.
