### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by PetruGarstea** [rm-hull/luma.led_matrix#152]
Greetings,

Are you plan supporting FreeBSD ?

Cheers,
Petru

**Comment by rm-hull** [comment]
I have no immediate plans to support freebsd nor have a use case for it. 

If it is not too invasive, remains compatible with mainstream rasbian operating systems, and you are willing to provide a PR for freebsd support, then I am happy to accept contributions.

**Comment by PetruGarstea** [comment]
Hi,

Thanks for turnaround. My knowledge here is 0. I will give a try, I will ask the community how to start and where to go.

Cheers
