### ISSUE TITLE
Whats the easiest way to display static text?

### ISSUE THREAD

**Issue by GYJohn** [rm-hull/luma.led_matrix#168]
Hello,

just a simple question:
Whats the easiest way to display static text?

Is it something like?:
```python
with canvas(device) as draw:
        draw.rectangle(device.bounding_box, outline="white")
        text(draw, (2, 2), "Hello", fill="white", font=proportional(LCD_FONT)
```

Normally i use:
```
show_message(device, msg, fill="white", font=proportional(CP437_FONT))
```
but this text is scrolling. I want just to display text on my LED's, without the moving action..

Thank you!

Regards

**Comment by thijstriemstra** [comment]
@GYJohn try `from PIL import ImageFont`

**Comment by GYJohn** [comment]
Traceback (most recent call last):
  File "testLED.py", line 9, in <module>
    font = ImageFont.truetype("examples/pixelmix.ttf", 8)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 280, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 145, in __init__
    layout_engine=layout_engine)
IOError: cannot open resource


Thanks for adding it into the docs :)

**Comment by rm-hull** [comment]
It's in the luma.examples repo: https://github.com/rm-hull/luma.examples/blob/master/examples/fonts/pixelmix.ttf

**Comment by GYJohn** [comment]
Ah nvm okey.
Any ideas for the "no output" problem?

**Comment by rm-hull** [comment]
Ok, so the default behaviour when your python program exits is to power off the LED matrix (as other programs may want to assume control of the GPIOs).

Try adding a `time.sleep(5)` to the after the `with canvas(...)`  line. [After it, rather than inside the block scope)
