### ISSUE TITLE
Implementing Code From DotMatrixTool

### ISSUE THREAD

**Issue by dh47** [rm-hull/luma.led_matrix#170]
Hello,

Is there anyway to take the code that has been generated from http://dotmatrixtool.com and implement it in python code for the dot matrix display?

**Comment by rm-hull** [comment]
Absolutely!

This is pretty much how the legacy font definitions are created. See https://github.com/rm-hull/luma.core/blob/master/luma/core/legacy/font.py#L81 for example.

You could create your own design in the dotmatrixtool website as follows:

![image](https://user-images.githubusercontent.com/1915543/49408658-13b96c80-f755-11e8-8a25-445693954eba.png)

Which gives us:

```c
const uint_8 data[] =
{
0x00, 0x3e, 0x08, 0x3e, 0x00, 0x3e, 0x2a, 0x22, 0x00, 0x3e, 0x20, 0x20, 0x00, 0x3e, 0x0a, 0x0e
};
```

Then copy pasting into Python:

```python
from luma.core.interface.serial import spi, noop
from luma.core.render import canvas
from luma.led_matrix.device import max7219
from luma.core import legacy

MY_CUSTOM_BITMAP_FONT = [
    # Paste byte code in here, remember to use square brackets rather than curlies...
    [ 0x00, 0x3e, 0x08, 0x3e, 0x00, 0x3e, 0x2a, 0x22, 0x00, 0x3e, 0x20, 0x20, 0x00, 0x3e, 0x0a, 0x0e ]
]

serial = spi(port=0, device=0, gpio=noop())
device = max7219(serial)

with canvas(device) as draw:
    # Note that "\0" is the zero-th character in the font (i.e the only one)
    legacy.text(draw, (0, 0), "\0", fill="white", font=MY_CUSTOM_BITMAP_FONT)
```

This is it running in the emulator:

![luma_000001](https://user-images.githubusercontent.com/1915543/49409126-161cc600-f757-11e8-82d0-f3303c970167.png)

With the following command: `python3 examples/dotmatrixtool.py -f conf/led_matrix.conf --width=16 --height=8` (I will publish the example source code shortly, but it more-or-less looks like the python above)

**Comment by sonic2wb** [comment]
totally Awesome @dh47 and I were working on this and you made it perfect!

**Comment by sonic2wb** [comment]
https://cdn.discordapp.com/attachments/517528896451641359/519432829990469633/VID_20181204_033937996.mp4

There is a video of a small animation we made.

**Comment by Rishikeshdaoo** [comment]
This is an awesome feature!
I wanted to make sort of an animation where it iteratively goes through each frame of the dot matrix. (similar to how @sonic2wb has shown in the comment above, just a lot more frames, one after the other)

Any pointers on how that could be achieved?
