### ISSUE TITLE
Support for 64x16 and 64x32 HUB08 monochrome led matrix

### ISSUE THREAD

**Issue by jonsito** [rm-hull/luma.led_matrix#185]
Hi all!
Here comes my own implementation for HUB08 monochrome 64x16 and 64x32 led matrices
luma.core.device driver 
These led matrix are very common, cheap and easy to adquire, but till now, only found support for Arduino

Some notes:
- Tested in Raspberry PI 3 with a 64x16 matrix
- Brightness is handled by mean of PWM on HUB08 "enable" signal. Need to fine-tune gamma-correction table and pwm frecuency to get it flicker-free
- Ideally SPI should be used. Instead, but due to dual (R1/R2) channels for rows (0..15) and (16..31), I reverted to "GPI mode" of feeding shift registers
- I use double buffering: display() renders in one buffer while matrix refresh works in the opposite one

Code available at:
https://github.com/jonsito/AgilityContest/blob/master/applications/RaspBerryPi_NowRunning/lib/hub08.py
VideoDemo and photo ( before wiring connections )  for my App:
https://filedn.com/lYQXisoneTfLFS1OSsl7lOy/AgilityContest/tripas_suturno.jpg
https://filedn.com/lYQXisoneTfLFS1OSsl7lOy/AgilityContest/demo_suturno.mov

Juan Antonio

**Comment by thijstriemstra** [comment]
thanks @jonsito. can you open a pull request and incorporate the new driver in a fork of this project?
