### ISSUE TITLE
max7219 package on pypi

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/luma.led_matrix#191]
when searching for luma.led_matrix, the max7219 package comes up first: https://pypi.org/project/max7219/

there's nothing on that pypi page (e.g. first paragraph) that tells me it's a deprecated package. Can this be updated and made more clear for new users?

**Comment by rm-hull** [comment]
Alternatively we could just delete all versions on pypi (same goes for https://pypi.org/project/ssd1306/)

**Comment by rm-hull** [comment]
@thijstriemstra Unless you (or anyone else) have specific objections, I will remove all max7219 and ssd1306 packages from pypi this weekend.

**Comment by thijstriemstra** [comment]
sounds good. i don't think there's a pypi-redirect option like github has..

**Comment by rm-hull** [comment]
Packages and all release versions removed from pypi.

**Comment by thijstriemstra** [comment]
RIP.
