### ISSUE TITLE
ImportError: No module named luma.led_matrix.device

### ISSUE THREAD

**Issue by FireWizard312** [rm-hull/luma.led_matrix#200]
So I just got the MAX7219, and just finished running the installation codes. However, when I ran python examples/matrix_demo.py, I got the error message:
Traceback (most recent call last):
  File "examples/matrix_demo.py", line 10, in <module>
    from luma.led_matrix.device import max7219
ImportError: No module named luma.led_matrix.device
I searched it up on the internet, and I checked #151 and followed the instructions. However, it still didn't work. Can you please help me?

**Comment by thijstriemstra** [comment]
did you manage to figure it out @FireWizard312

**Comment by FireWizard312** [comment]
I just had to use python3.
