### ISSUE TITLE
Question: Is it possible to scroll the text from left to right?

### ISSUE THREAD

**Issue by n0rb33r7** [rm-hull/luma.led_matrix#203]
Dear Developers!

Thank you for doing this project, it's really great and I do appreciate your work.

I'm trying to create this project: https://hackaday.io/project/12084/instructions

I already soldered all the parts, but I'm not able to do the scrolling properly as the led.py which was provided in linked project is not compatible with the new version of luma.led_matrix. 

In order to make it work (to change the direction of the scrolling) was needed by doing the following change in led.py 

Out:
```python
self.scroll_ left (redraw = false)
self._buffer [-1] = value
```
Becomes:
```python
self.scroll_ right (redraw = false)
self._buffer [1] = value
```
But the new code is already way different and I'm not able to decipher how I could change the direction of the scrolling.

Could you please help?

Thank you

**Comment by rm-hull** [comment]
Please take a look at the [examples](https://github.com/rm-hull/luma.led_matrix/tree/master/examples)
