### ISSUE TITLE
Changement pins and use both spi Ports

### ISSUE THREAD

**Issue by paulvanderheijden90** [rm-hull/luma.led_matrix#204]
I see the issue using different pins.
‘’Possibility to use differents pins #169’’

 **Quoot:**

> OK, I understand ! Then, if I use the port 1, I've to use
> GPIO 20 (P38) instead of GPIO 10 (MOSI)
> GPIO 18 (P12) instead of GPIO 8 (SPI CE0)
> GPIO 21 (P40) instead of GPIO 11 (SPI CLK)
> 
> It's works great !
> Thanks !

So by changing   serial = spi(port=0, device=0, gpio=noop()). To 
  serial = spi(port=1, device=0, gpio=noop())
Will activate the second pins provide on te Raspberry.????

Is it also posible to use them both for the 7219 matrix?
So i can program 2 lines of matrixes. Like this:

```python
create matrix device
    serial1 = spi(port=0, device=0, gpio=noop())
    device1 = max7219(serial1, cascaded=n or 1, block_orientation=block_orientation,
                     rotate=rotate or 0, blocks_arranged_in_reverse_order=inreverse)
    print("Created device1")

create matrix device
    serial2 = spi(port=1, device=0, gpio=noop())
    device2 = max7219(serial2, cascaded=n or 1, block_orientation=block_orientation,
                     rotate=rotate or 0, blocks_arranged_in_reverse_order=inreverse)
    print("Created device2")

msg1 = "Slow scrolling: This will be matrix string no 1"
    print(msg1)
    show_message(device1, msg1, fill="white", font=proportional(LCD_FONT), scroll_delay=0.1)

msg2 = "Slow scrolling: this wil be matrix chain no2"
    print(msg2)
    show_message(device2, msg2, fill="white", font=proportional(LCD_FONT), scroll_delay=0.1)
```

Please let me know if im right with this

**Comment by rm-hull** [comment]
Seems reasonable; try it !!

**Comment by paulvanderheijden90** [comment]
Oké i let you know!!

**Comment by paulvanderheijden90** [comment]
Oke i tryed 

`from luma.core.interface.serial import spi, noop
from luma.core.render import canvas
from luma.core.virtual import viewport
from luma.led_matrix.device import max7219
from luma.core.legacy import text, show_message
from luma.core.legacy.font import proportional, CP437_FONT, LCD_FONT

serial1 = spi(port=0, device=0, gpio=noop())
device1 = max7219(serial1, width=32, height=8, block_orientation=-90)
#device1.contrast(2)
virtual1 = viewport(device1, width=32, height=8)

serial2 = spi(port=0, device=1, gpio=noop())
device2 = max7219(serial2, width=32, height=8, block_orientation=-90)
#device2.contrast(15)
virtual2 = viewport(device2, width=32, height=8)

#show_message(device1, 'Raspberry Pi MAX7219', fill="white", font=proportional(LCD_FONT), scroll_delay=0.08)

#show_message(device2, 'ik ben paul', fill="white", font=proportional(LCD_FONT), scroll_delay=0.08)

while True:
    with canvas(virtual1) as draw:
        text(draw, (0, 1), "Paul", fill="white", font=proportional(LCD_FONT))
            #text(draw, (0, 1), datetime.now().strftime('%I:%M'), fill="white", font=proportional(CP437_FONT))
    with canvas(virtual2) as draw:
        text(draw, (0, 1), "Paul", fill="white", font=proportional(LCD_FONT))
    device1.contrast(15)
    device2.contrast(5)

`

**Comment by paulvanderheijden90** [comment]
Hello I found out that the Contrast has to be (15*16) then it is working.
