### ISSUE TITLE
Question: Is it possible to split the MAX7219 into individual LED lights, or connect individual LED lights to the MAX7219

### ISSUE THREAD

**Issue by FireWizard312** [rm-hull/luma.led_matrix#206]
So I recently wrote a code that would help identify where certain things are. The problem is, I use LED lights to tell where each of the items is. Since the MAX7219 can't be attached to each box that has each item, is it possible to separate the MAX7219 into individual LED lights that can be controlled using the same code for a regular MAX7219? Keep in mind that I need about 128 LED lights to make this work.

**Comment by rm-hull** [comment]
If you can source a max7219 chip, and a bunch of LEDs then there is no reason why it wouldn't work. All the MAX7219 is multiplex over the 8 rows and 8 columns repeatedly. The LED matrix will be arranged something like this:

![image](https://user-images.githubusercontent.com/1915543/70395678-282fe500-19f9-11ea-9cf9-59f9380faf48.png)

**Comment by rm-hull** [comment]
To be fair, I would just buy a strip of ws2812b leds - they are wired in series so it would be much less hassle than lots of wires, and you would get programmable color RGBs to boot

**Comment by FireWizard312** [comment]
Its just that i need 128 lights
