### ISSUE TITLE
Adding brightness/contrast parameter to max7219 init method

### ISSUE THREAD

**Issue by snarkywolverine** [rm-hull/luma.led_matrix#207]
Can contrast level be an optional parameter on the constructor for the max7219?

I have a script that re-inits and updates the display every so often; every time it runs, I see a brief 'flash' where the contrast is raised before my code can lower it again.  If contrast was an optional parameter, I could eliminate that "flashing".

**Comment by rm-hull** [comment]
Yep that seems a good feature request (and simple to implement)

**Comment by rm-hull** [comment]
1.4.1 released to PyPI with this change
