### ISSUE TITLE
luma.led_matrix on Nvidia's Jetson platform

### ISSUE THREAD

**Issue by JeredWilloughby** [rm-hull/luma.led_matrix#227]
I was wondering if you have time for a quick question? I’m working with the Jetson platforms Nano & Xavier, where I have successfully built and trained and custom object detector. I’m trying to send a custom message to a Max7219 led matrix (https://www.amazon.com/Onyehn-MAX7219-Display-Arduino-Microcontroller/dp/B07KQ31FX6/ref=sr_1_3?dchild=1&keywords=max7219&qid=1596059608&sr=8-3), but can’t seem to get it to work on the Jetsons platforms. I have successfully configured the gpio pin’s via the terminal (sudo /opt/nvidia/jetson-io/jetson-io.py). I followed a tutorial and installed all the dependencies: sudo apt-get install python3-pip
$ pip3 install adafruit-blinka
$ pip3 install adafruit-circuitpython-busdevice
$ pip3 install adafruit-circuitpython-rgb-display
$ sudo apt-get install python3-pil

Although, I think they’re for an led/lcd display from adafruit. I have also installed all of the dependencies from the this potential solution: https://pypi.org/project/luma.led_matrix/ and https://luma-led-matrix.readthedocs.io/en/latest/python-usage.html#x8-led-matrices.

Can anyone help shed some light where this is going wrong?

**Comment by thijstriemstra** [comment]
This library is targeted at Raspberry Pi (and Raspbian).
