### ISSUE TITLE
Display accented characters

### ISSUE THREAD

**Issue by cyrilbosson** [rm-hull/luma.led_matrix#248]
Hello,

I like to use accented characters, I tried all 3 texts fonts (LCD, TINY & SINCLAIR) but it doesn't work.
I read the documentation but I don't understand how to use an custom font.

Is it possible? Can I extend any font to add accents?

Thanks a lot

**Comment by marcowy** [comment]
Try this:
https://github.com/rm-hull/luma.led_matrix/issues/170
and this:
https://github.com/rm-hull/luma.led_matrix/issues/111
