### ISSUE TITLE
Matrix max7219 : Rotate font for vertical display

### ISSUE THREAD

**Issue by fred2nice** [rm-hull/luma.led_matrix#252]
Hi Richard, 

Thank your for the module, everything works fine !

I put my 4x4 in vertical position, scrolling is ok but I would like to rotate letters to have  :
H
E
L
L
O

But I have this :
![IMG_6934](https://user-images.githubusercontent.com/25772276/125178135-22f0d880-e1e2-11eb-95a7-ef090ee4bdfe.jpg)

Do you have a magic option somewhere ? a special font ?

Kind Regards.
Frederic

**Comment by thijstriemstra** [comment]
@fred2nice use the `rotate` parameter (in degrees):

```python
device = max7219(serial, width=w, height=h, rotate=180)
```

**Comment by fred2nice** [comment]
Hi, 

If I use rotate=2 ( 180°) without block_orientation=-90 the message is displayed on each block ( letters displayed correctly) , what I would like is a scrolling bottom to top, if I add block_orientation=-90 the scrolling is fine, but letters are in wrong orientation.
 
```
import time
from luma.core.interface.serial import spi, noop
from luma.led_matrix.device import max7219
from luma.core.legacy import show_message
from luma.core.legacy.font import proportional, CP437_FONT


serial = spi(port=0, device=0, gpio=noop())
device = max7219(serial,rotate=2,cascaded=4,block_orientation=-90)
show_message(device, "Hello !!!", fill="white", font=proportional(CP437_FONT), scroll_delay=0.05)
time.sleep(1)

```
