### ISSUE TITLE
ModuleNotFoundError: No module named 'luma.led_matrix' when runing python examples/matrix_demo.py -h  

### ISSUE THREAD

**Issue by hathemi** [rm-hull/luma.led_matrix#261]
#### Type of Raspberry Pi
raspberry pi4
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 

#### Linux Kernel version
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

#### Expected behaviour
> Add a few concise notes about what you are expecting to happen.
> Even better, if you paste in a code sample that demonstrates what you want to achieve.

#### Actual behaviour
 $ pip list | grep luma
luma.core         2.3.2
luma.led-matrix   1.5.0

i have folowed all the instruction in this link https://luma-led-matrix.readthedocs.io/en/latest/install.html , but in th end, i have got this error bilow 

> 
> pi@raspberrypi:~/max7219 $ python examples/sevensegment_demo.py
> Traceback (most recent call last):
>   File "/home/pi/max7219/examples/sevensegment_demo.py", line 13, in <module>
>     from luma.led_matrix.device import max7219
> ModuleNotFoundError: No module named 'luma.led_matrix'
> 
> pi@raspberrypi:~/max7219 $ python examples/matrix_demo.py -h
> Traceback (most recent call last):
>   File "/home/pi/max7219/examples/matrix_demo.py", line 10, in <module>
>     from luma.led_matrix.device import max7219
> ModuleNotFoundError: No module named 'luma.led_matrix'

how can i fix it please ?

**Comment by thijstriemstra** [comment]
@hathemi can you try to install it again and paste output here, there is probably some error related to #260
