### ISSUE TITLE
No Module Named 'luma.led_matrix'

### ISSUE THREAD

**Issue by LukeVarty** [rm-hull/luma.led_matrix#273]
Hello,

I've seen this issue a couple of times but have tried all solutions and nothing has worked for me.

If I try and run any of the examples, I get this error and unable to go any further.

The command I am using is
`sudo python3 silly_clock.py`

Please could you let me know if there is any other solutions I can try!

**Comment by rm-hull** [comment]
Sorry but there is not really enough information here. When you said "tried all the solutions" im not sure what that means, as there is only one recommended way as per the install instructions https://luma-led-matrix.readthedocs.io/en/latest/install.html#installing-from-pypi
