### ISSUE TITLE
Add progress indicator(s)

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.led_matrix#31]
Animated spinny-thing, for both 8x8 matrices and 7-segment displays.

**Comment by thijstriemstra** [comment]
Would be cool to have support for https://github.com/WoLpH/python-progressbar or some other existing progress library.

**Comment by rm-hull** [comment]
mmm ... interesting, I had a brief scan of the code, and it looks like it _could_ be quite straightforward: my first though was maybe just extending the `ProgressBar` class to override the update method to send output to a device (or series of cascaded devices).

**Comment by thijstriemstra** [comment]
@rm-hull sounds good. let's not re-invent tha wheel!

**Comment by rm-hull** [comment]
On reflection, I think this functionality should probably lie outside the library.
