### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.led_matrix#53]
Typically simple regression tests to check existing behaviour doesn't break, with mocks where appropriate

**Comment by thijstriemstra** [comment]
looks fixed.

**Comment by rm-hull** [comment]
yah, nearly ... but I'm procrastinating over this https://github.com/rm-hull/luma.led_matrix/blob/feature/show_message_test/tests/test_legacy.py#L55-L77, as not sure the best way to proceed ...
