### ISSUE TITLE
Mock assert_called() fails on py35 only

### ISSUE THREAD

**Issue by rm-hull** [rm-hull/luma.led_matrix#70]
See FIXME's in `tests/test_neopixel.py`

**Comment by thijstriemstra** [comment]
Is this visible on travis?

**Comment by rm-hull** [comment]
Can't find the failed builds on the led_matrix repo, but heres a similar one on luma.oled: https://travis-ci.org/rm-hull/luma.oled/builds/196357642

**Comment by thijstriemstra** [comment]
`assert_called` isn't documented on https://docs.python.org/3.5/library/unittest.mock.html. `assert_called_with` is and I think this should be used instead. Making a PR now.

**Comment by thijstriemstra** [comment]
There's actually a `called` boolean that looks better: https://docs.python.org/3.5/library/unittest.mock.html#unittest.mock.Mock.called

**Comment by thijstriemstra** [comment]
See https://github.com/rm-hull/luma.oled/pull/132 for luma.oled, working on luma.led_matrix PR now.
